config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'books#index'












  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true, length: { minimum: 4}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private
  def record_not_found
    render file: 'public/404.html',
           layout: false,
           status: :not_found
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :edit, :uptate, :delete]

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    #整理 creat update 的清洗 book_params代入
    @book = Book.new(book_params)

    if @book.save
      redirect_to root_path, notice: "新增成功啦 Mother Fucker"
    else
      render new_book_path
    end
  end

  def show
    #原本有 @book = Book.find(params[:id]) 有BA之後可不寫
  end

  def edit
    #原本有 @book = Book.find(params[:id]) 有BA之後可不寫
  end

  def update

    #整理 creat update 的清洗 book_params代入
    #原本有 @book = Book.find(params[:id]) 有BA之後可不寫
    if @book.update(book_params)
      redirect_to root_path, notice: "更新完成"
    else
      render :edit, notice: "更新失敗"
    end
  end

  def destroy
    #原本有 @book = Book.find(params[:id]) 有BA之後可不寫
    @book.destroy
    redirect_to root_path notice: "書籍已刪除"
  end

  private

  def find_book
    @book = Book.find(params[:id])
    # 可取代 show edit update delete
    #用before_action(BA) 強制先行
  end

  def book_params
    params.require(:book).permit(:title)
    #整理 creat update 的清洗
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<% if book.errors.any? %>
<ul>
<% book.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>
</ul>
<% end %>



<%= form_for(book) do |f| %>
  <%= f.text_field :title %>
  <%= f.submit "新增變更書名" %>
  <% end %>

<%# #底線檔不要用實體變數 這邊@要拿掉 但是不能運作 要從render改 %>
<%# #有類似的需求 ex:多個廣告 讓各自的頁面去抓對應的變數來這邊代入 稱局部渲染 所以不一開始就用實體變數主動去抓  %>

app/views/books/edit.html.erb
<h1>編輯書本</h1>

<%= render 'form' , book = @book %>
<%# #與new太像 合併模組化進去form %>
<%# render book = @book 解決底線檔不用實體變數 %>

app/views/books/index.html.erb
<h1>書籍列表</h1>

<%= link_to "新增書籍", new_book_path %> 



<ul class="booklist">
<% @books.each do |book| %>
<li>
<%= link_to "編輯", edit_book_path(book) %>  <%# #book.id不用寫id path會自動幫忙長出來 而且省略完之後book_path(book)可以再省變成book%>
<%= link_to "刪除", book,            
                    #method: 'delete',
                    data: { confirm: '是否確定刪除？' } %>
<%= link_to book.title, book %>    <%# #book.id不用寫id path會自動幫忙長出來 而且省略完之後book_path(book)可以再省變成book%>
</li>
<% end %>
</ul>

app/views/books/new.html.erb
<h1>新增書籍</h1>

<%= render 'form' , book = @book %>

<%# #與edit太像 合併模組化進去form %>
<%# render book = @book 解決底線檔不用實體變數 %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>

app/views/layouts/application.html.erb
  
<!DOCTYPE html>
<html>
  <head>
    <title>smdbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <%= render "share/navbar"%>   
   <%= render "share/watch" if notice %>   
  
    <%= yield %>
  </body>
</html>

app/views/share/_navbar.html.erb
<nav>
    <ul>
        <li><%= link_to "首頁",root_path %></li>
        <li><%= link_to "書籍列表",books_path %></li>
        <ul>
</nav>

<%# 模組化 外插表頭 %>

app/views/share/_watch.html.erb
 <%= notice %></p>


 <%# 模組化 外插快閃警語 %>